# Default values for learning-locker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

api:
  enabled: true
  fullnameOverride: learning-locker-api

ui:
  enabled: true
  fullnameOverride: learning-locker-ui
  apiHost: learning-locker-api

worker:
  enabled: true
  fullnameOverride: learning-locker-worker

global:
  secretName: learning-locker-secret
