apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "worker.fullname" . }}"
  labels:
{{ include "worker.labels" . | indent 4 }}
data:
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  REDIS_DB: "{{ .Values.redis.db }}"
